language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id:
    secure: auLKkQ4YSinW8agM9RawIt/bE4pcad1cCxm1/qJH7OtxvVp3ioFZEJO2Q80eRsGkqTsn6D7PfpYbRldtkqXKT0EOdrvrvkV5l1ppdpWsaAYXATw8QftMuSpaYNfW8f7J0FvqrmuC31rRG/JDf7hgB3kgyXTR8qtaxZot8b9z7vOTpa4uLBqjKA5kTpryIXYoV7Mn65xEbIV6do/5Mo+w/0Kr7Sloax6YZZQRpFaLHMXUEZSrvwHd9bVcesR7eScFektXErqMFWfdb/sefpfpq9ekRbsS6koWm0hZEFDQVgeWqLb90s7yHiXhOc0Egtvrrj/kIL/rT/5PXUwGY/JbI6By5p0PqvZ4lho4hsWOOQI8SHbiR/ZTUnJXiqW3CHAlQsezWuEsc9OhRQueDobSQ7k3IjtuOHvZT2Q2wods/+FMNrhkyUquISsiOL8AkXQ8qaabBL9d4pNKSwq7wCdkOetCvFUR7M9YCgmbEU5FLNVNiMl4fX9KFEla4/e8foqkTljGooaKLwT9GiFM8+Ef/Jc4btutRAB1I6CIOEKVoI8FNBQe466PrjDF2xmiET78DPSVJfgYcTCkY02pVWEmJZOa/g5gZBfQ0JWS2z5eratHgiy/a2Gkmlhw9tQZy6YuFlKdM5i62NYdNHxq9Q0ySt4XJi7bIQOTMxWRo99xOWU=
  secret_access_key:
    secure: gZtBcluVFjg+DXN0lUlyd3lKN0QPK/lVcTySQ16Mq7RVVlXTqmcjE7gPqfnjtf4StwvjFpL54bti8BMNi7i1+gxRca/nogx52ZP69w3O39yEi6bqCxAXMLliSpQ4PIm9lfmRGd6xlLXoXjCeXDCJY4FecdnHR2ShzZKq2GfWv5cUwb9OvcHvd8yUE8e/yI4xK27NnuSh2APRnOWjCOInGDZGdfPeX9Dr6PZCq2L24FT6sCc7oz75YE3Wa1etxJ9VH1VPtYB/E/T0XT/sxVmIJTuFJ2voxmhpy/b9oFADukh9CzYPXbueTA5OL9qIwYo+oSj1BrE3fkDd73OIz469ApyxFfApXl0HdyRAYhdMDpCrYQVQrxus8Lx9YVG1vnSaVfwoyE6C9PaMbnleDbKF4Imds5JTT1sMIqR0pSkGunjL3nXaDbxHaYBIjmHyapysIJgKZ7giD6M5DIt2JvhMAOmHQ7zR/7VE0DkgqnWugA1l4RGnhoxjZ/rNwGTTtueI9bXveph/x0i8XYPVKG7dTlKUvBcaJEyHl/2kDPF3ADK8kdfr+EwNwOQGCU+aISTM1m7B0J6FPetSt+rlZWqth4uUDjinEIRybITyocrEQH1Oog9wj1B+CwPIeIM+SMON8HnKrFm3IiHAHKLWpxPSQzMBX5U42uUeoN0CsUn3NwU=
  skip_cleanup: true
  local_dir: build
  default_text_charset: utf-8
  bucket: static-react
  region: us-east-1
